# Generated by Django 3.0.3 on 2020-02-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200218_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
