# Generated by Django 3.0.3 on 2020-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20200218_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_id',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
