# Generated by Django 3.0.3 on 2020-02-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20200218_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='types',
        ),
    ]
