# Generated by Django 3.0.3 on 2020-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=40, unique=True)),
                ('bufferLevel', models.IntegerField()),
                ('leadTime', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
